version: '3.8'

services:
  gateway:
    image: nginx:alpine
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
      - user-service
      - company-service
      - ticketing-service
      - qr-service
      - payment-service
    networks:
      - ticketing-net

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: itbienvenu
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: ticketing_system
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ticketing-net

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    networks:
      - ticketing-net

  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    environment:
      - DATABASE_URL=postgresql://itbienvenu:123@postgres:5432/ticketing_system
      - JWT_SECRET=supersecretkey
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    networks:
      - ticketing-net

  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    environment:
      - DATABASE_URL=postgresql://itbienvenu:123@postgres:5432/ticketing_system
    ports:
      - "8002:8002"
    depends_on:
      - postgres
    networks:
      - ticketing-net

  company-service:
    build:
      context: .
      dockerfile: services/company-service/Dockerfile
    environment:
      - DATABASE_URL=postgresql://itbienvenu:123@postgres:5432/ticketing_system
    ports:
      - "8003:8003"
    depends_on:
      - postgres
    networks:
      - ticketing-net

  ticketing-service:
    build:
      context: .
      dockerfile: services/ticketing-service/Dockerfile
    environment:
      - DATABASE_URL=postgresql://itbienvenu:123@postgres:5432/ticketing_system
      - TICKET_SECRET_KEY=superqrsecret
    ports:
      - "8004:8004"
    depends_on:
      - postgres
    networks:
      - ticketing-net

  qr-service:
    build:
      context: .
      dockerfile: services/qr-service/Dockerfile
    environment:
      - DATABASE_URL=postgresql://itbienvenu:123@postgres:5432/ticketing_system
      - TICKET_SECRET_KEY=superqrsecret
    ports:
      - "8005:8005"
    depends_on:
      - postgres
    networks:
      - ticketing-net

  payment-service:
    build:
      context: .
      dockerfile: services/payment-service/Dockerfile
    environment:
      - DATABASE_URL=postgresql://itbienvenu:123@postgres:5432/ticketing_system
    ports:
      - "8006:8006"
    depends_on:
      - postgres
    networks:
      - ticketing-net

networks:
  ticketing-net:
    driver: bridge

volumes:
  postgres_data:
